openapi: 3.1.0
info:
  title: Error Schemas
  version: 1.0.0
components:
  schemas:
    InternalServerError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Internal Server Error
        errorCode:
          type: string
          enum: ["INTERNAL_SERVER_ERROR"]
          example: INTERNAL_SERVER_ERROR
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    ForbiddenError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Access denied, you do not have permission to perform this action.
        errorCode:
          type: string
          enum: ["ACCESS_FORBIDDEN"]
          example: ACCESS_FORBIDDEN
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    TooManyRequestsError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Too many requests. Please try again later.
        errorCode:
          type: string
          enum: ["TOO_MANY_REQUESTS"]
          example: TOO_MANY_REQUESTS
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    EmailServiceError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Failed to send the email. Please try again later.
        errorCode:
          type: string
          enum: ["EMAIL_SERVICE_ERROR"]
          example: EMAIL_SERVICE_ERROR
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    InvalidRequestBodyValidationError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
        - errors
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Validation failed, some fields in the request body did not meet the expected format or constraints.
        errorCode:
          type: string
          enum: ["VALIDATION_ERROR_INVALID_REQUEST_BODY"]
          example: VALIDATION_ERROR_INVALID_REQUEST_BODY
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
        errors:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
              message:
                type: string
          example:
            - field: email
              message: Invalid email address
            - field: password
              message: Password must be at least 8 characters
    EmailAlreadyExistsError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Registration failed, this email address is already associated with an existing account.
        errorCode:
          type: string
          enum: ["AUTH_EMAIL_ALREADY_EXISTS"]
          example: AUTH_EMAIL_ALREADY_EXISTS
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    UserNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: User with the specified email was not found.
        errorCode:
          type: string
          enum: ["AUTH_USER_NOT_FOUND"]
          example: AUTH_USER_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    InvalidCredentialsError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Invalid credentials. Please check your email and password and try again.
        errorCode:
          type: string
          enum: ["AUTH_INVALID_CREDENTIALS"]
          example: AUTH_INVALID_CREDENTIALS
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasswordReuseNotAllowed:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: You cannot reuse a previous password. Please choose a new one.
        errorCode:
          type: string
          enum: ["AUTH_PASSWORD_REUSE_NOT_ALLOWED"]
          example: AUTH_PASSWORD_REUSE_NOT_ALLOWED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    VerificationCodeNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Invalid or non-existent verification code. Please request a new one.
        errorCode:
          type: string
          enum: ["VERIFICATION_CODE_ERROR_CODE_NOT_FOUND"]
          example: VERIFICATION_CODE_ERROR_CODE_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    VerificationCodeExpiredError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: This verification code has expired. Please request a new one to continue.
        errorCode:
          type: string
          enum: ["VERIFICATION_CODE_ERROR_CODE_EXPIRED"]
          example: VERIFICATION_CODE_ERROR_CODE_EXPIRED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    VerificationCodeConsumedError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: This verification code has already been used. Please request a new one if needed.
        errorCode:
          type: string
          enum: ["VERIFICATION_CODE_ERROR_CODE_CONSUMED"]
          example: VERIFICATION_CODE_ERROR_CODE_CONSUMED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, no authentication token provided.
        errorCode:
          type: string
          enum: ["AUTH_ACCESS_TOKEN_NOT_FOUND"]
          example: AUTH_ACCESS_TOKEN_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenUserNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the user associated with this token does not exist.
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_USER_NOT_FOUND"]
          example: AUTH_TOKEN_USER_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenInvalidSessionError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the token session is invalid, expired, or has already been consumed.
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_SESSION_INVALID"]
          example: AUTH_TOKEN_SESSION_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenSessionMismatchError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the user ID in the MFA token does not match the user ID of the session.
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_SESSION_MISMATCH"]
          example: AUTH_TOKEN_SESSION_MISMATCH
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenInvalidTokenErorr:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
        message:
          type: string
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_INVALID"]
        requestId:
          type: string
      examples:
        jwtMalformed:
          summary: Token is malformed
          value:
            success: false
            message: "Authentication failed: jwt malformed"
            errorCode: AUTH_TOKEN_INVALID
            requestId: cc5065df0c6b4c19970d4e92f
        invalidSignature:
          summary: Token signature is invalid
          value:
            success: false
            message: "Authentication failed: invalid signature"
            errorCode: AUTH_TOKEN_INVALID
            requestId: cc5065df0c6b4c19970d4e92f
        tokenMissing:
          summary: Token is missing
          value:
            success: false
            message: "Authentication failed: jwt must be provided"
            errorCode: AUTH_TOKEN_INVALID
            requestId: cc5065df0c6b4c19970d4e92f
        invalidAudience:
          summary: Token audience does not match
          value:
            success: false
            message: "Authentication failed: invalid audience"
            errorCode: AUTH_TOKEN_INVALID
            requestId: cc5065df0c6b4c19970d4e92f
        invalidIssuer:
          summary: Token issuer is invalid
          value:
            success: false
            message: "Authentication failed: invalid issuer"
            errorCode: AUTH_TOKEN_INVALID
            requestId: cc5065df0c6b4c19970d4e92f
    AuthenticationTokenExpiredError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, jwt expired at 2025-11-02T18:00:00Z.
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_EXPIRED"]
          example: AUTH_TOKEN_EXPIRED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AccessTokenTypeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, expected an ACCESS token, but received a token of a different type.
        errorCode:
          type: string
          enum: ["AUTH_ACCESS_TOKEN_TYPE_INVALID"]
          example: AUTH_ACCESS_TOKEN_TYPE_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MFATokenTypeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, expected an MFA token, but received a token of a different type.
        errorCode:
          type: string
          enum: ["AUTH_MFA_TOKEN_TYPE_INVALID"]
          example: AUTH_MFA_TOKEN_TYPE_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MFATokenInvalidEndpointError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, MFA token was sent to an invalid or unsupported endpoint.
        errorCode:
          type: string
          enum: ["AUTH_MFA_INVALID_ENDPOINT"]
          example: AUTH_MFA_INVALID_ENDPOINT
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MFATokenInvalidTokenPurposeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, MFA token purpose mismatch. Expected 'login', got 'forgot_password'.
        errorCode:
          type: string
          enum: ["AUTH_TOKEN_INVALID_TYPE"]
          example: AUTH_TOKEN_INVALID_TYPE
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MagicLinkTokenTypeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, expected an MAGIC-LINK token, but received a token of a different type.
        errorCode:
          type: string
          enum: ["AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID"]
          example: AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    RefreshTokenTypeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, expected an REFRESH token, but received a token of a different type.
        errorCode:
          type: string
          enum: ["AUTH_REFRESH_TOKEN_TYPE_INVALID"]
          example: AUTH_REFRESH_TOKEN_TYPE_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    RefreshTokenInvalidSessionError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the refresh token session does not exist or is invalid. Please log in again.
        errorCode:
          type: string
          enum: ["AUTH_REFRESH_TOKEN_SESSION_INVALID"]
          example: AUTH_REFRESH_TOKEN_SESSION_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    RefreshTokenExpiredSessionError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the refresh token session has expired. Please log in again to obtain a new refresh token.
        errorCode:
          type: string
          enum: ["AUTH_REFRESH_TOKEN_SESSION_EXPIRED"]
          example: AUTH_REFRESH_TOKEN_SESSION_EXPIRED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    AccessTokenTypeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, expected an ACCESS token, but received a token of a different type.
        errorCode:
          type: string
          enum: ["AUTH_ACCESS_TOKEN_TYPE_INVALID"]
          example: AUTH_ACCESS_TOKEN_TYPE_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MfaAlreadyEnabledError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Two-factor authentication is already enabled. No further action is required.
        errorCode:
          type: string
          enum: ["MFA_ALREADY_ENABLED"]
          example: MFA_ALREADY_ENABLED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MfaAlreadyDisabledError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Two-factor authentication is already disabled. No further action is required.
        errorCode:
          type: string
          enum: ["MFA_ALREADY_DISABLED"]
          example: MFA_ALREADY_DISABLED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MfaTemporarySecretExpiredError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Temporary TOTP secret expired. Please generate a new QR code to configure 2FA.
        errorCode:
          type: string
          enum: ["MFA_EXPIRED_TEMP_SECRET"]
          example: MFA_EXPIRED_TEMP_SECRET
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MfaInvalidverificationCodeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: The MFA code you entered is incorrect or has expired. Please request a new code to complete the verification.
        errorCode:
          type: string
          enum: ["MFA_INVALID_VERIFICATION_CODE"]
          example: MFA_INVALID_VERIFICATION_CODE
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    MfaNotEnabledError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Cannot verify MFA because two-factor authentication is not enabled for this account.
        errorCode:
          type: string
          enum: ["MFA_NOT_ENABLED"]
          example: MFA_NOT_ENABLED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    InvalidBackupCodeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: The backup code you entered is invalid or has already been used. Please try a different one.
        errorCode:
          type: string
          enum: ["BACKUPCODE_INVALID_CODE"]
          example: BACKUPCODE_INVALID_CODE
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    OIDCSessionNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, no valid OIDC session was found for the given state and provider.
        errorCode:
          type: string
          enum: ["OIDC_SESSION_NOT_FOUND"]
          example: OIDC_SESSION_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    OIDCSessionExpiredError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the OIDC session has expired. Please restart the sign-in process.
        errorCode:
          type: string
          enum: ["OIDC_SESSION_CONSUMED"]
          example: OIDC_SESSION_CONSUMED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    OIDCSessionConsumedError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the OIDC session has already been used and cannot be reused.
        errorCode:
          type: string
          enum: ["OIDC_SESSION_CONSUMED"]
          example: OIDC_SESSION_CONSUMED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    OIDCFailedAuthenticationError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed while communicating with the external identity provider. Please try again or use a different sign-in method.
        errorCode:
          type: string
          enum: ["OIDC_FAILED_AUTHENTIFICATION"]
          example: OIDC_FAILED_AUTHENTIFICATION
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyChallengeSessionNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the passkey registration session was not found or is invalid. Please restart the passkey process.
        errorCode:
          type: string
          enum: ["PASSKEY_CHALLENGE_SESSION_INVALID"]
          example: PASSKEY_CHALLENGE_SESSION_INVALID
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyChallengeSessionConsumedError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the passkey session has already been used. Please restart the passkey process.
        errorCode:
          type: string
          enum: ["PASSKEY_CHALLENGE_SESSION_CONSUMED"]
          example: PASSKEY_CHALLENGE_SESSION_CONSUMED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyChallengeSessionInvalidPurposeError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the passkey session purpose does not match the expected type. Please restart the passkey process.
        errorCode:
          type: string
          enum: ["PASSKEY_CHALLENGE_SESSION__INVALID_PURPOSE"]
          example: PASSKEY_CHALLENGE_SESSION__INVALID_PURPOSE
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyChallengeSessionExpiredError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the passkey session has expired. Please restart the passkey process.
        errorCode:
          type: string
          enum: ["PASSKEY_CHALLENGE_SESSION__EXPIRED"]
          example: PASSKEY_CHALLENGE_SESSION__EXPIRED
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyChallengeVerificationError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the passkey verification could not be completed successfully. Please ensure you are using the correct passkey and try again.
        errorCode:
          type: string
          enum: ["PASSKEY_CHALENGE_VERIFICATION_ERROR"]
          example: PASSKEY_CHALENGE_VERIFICATION_ERROR
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    PasskeyNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Authentication failed, the provided passkey could not be found or is invalid. Please remove this passkey from your device and register a new one.
        errorCode:
          type: string
          enum: ["PASSKEY_NOT_FOUND"]
          example: PASSKEY_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    UserSessionNotFoundError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: The session associated with this operation could not be found.
        errorCode:
          type: string
          enum: ["AUTH_SESSION_NOT_FOUND"]
          example: AUTH_SESSION_NOT_FOUND
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
